[2023-10-14T11:40:26.847+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:40:20.731025+00:00 [queued]>
[2023-10-14T11:40:26.852+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:40:20.731025+00:00 [queued]>
[2023-10-14T11:40:26.853+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T11:40:26.853+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-14T11:40:26.853+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T11:40:26.859+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_table> on 2023-10-14 11:40:20.731025+00:00
[2023-10-14T11:40:26.864+0000] {standard_task_runner.py:55} INFO - Started process 1487 to run task
[2023-10-14T11:40:26.866+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigquery_data_load', 'create_table', 'manual__2023-10-14T11:40:20.731025+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_data_load.py', '--cfg-path', '/tmp/tmp09vh4ol0']
[2023-10-14T11:40:26.867+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask create_table
[2023-10-14T11:40:26.901+0000] {task_command.py:388} INFO - Running <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:40:20.731025+00:00 [running]> on host 4c2fe63b7c62
[2023-10-14T11:40:26.937+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Niko
AIRFLOW_CTX_DAG_ID=bigquery_data_load
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-10-14T11:40:20.731025+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-14T11:40:20.731025+00:00
[2023-10-14T11:40:26.938+0000] {bigquery.py:1077} INFO - Executing: 
        SELECT * except (rank)
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY vehicle_id ORDER BY DATE_TIME(date, TIME(hour, minute, 0)) DESC
                ) as rank
            FROM `***-400718.vehicle_analytics.history`) as latest
        WHERE rank = 1;
        
[2023-10-14T11:40:26.938+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-14T11:40:26.940+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:2051 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-10-14T11:40:26.940+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2023-10-14T11:40:26.942+0000] {bigquery.py:1542} INFO - Inserting job ***_1697283626942444_1f52de9e4cedebeb65456d77e49e6a29
[2023-10-14T11:40:28.093+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1103, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2185, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1548, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Function not found: DATE_TIME; Did you mean datetime? at [7:54]

Location: europe-central2
Job ID: airflow_1697283626942444_1f52de9e4cedebeb65456d77e49e6a29

[2023-10-14T11:40:28.122+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigquery_data_load, task_id=create_table, execution_date=20231014T114020, start_date=20231014T114026, end_date=20231014T114028
[2023-10-14T11:40:28.139+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task create_table (400 Function not found: DATE_TIME; Did you mean datetime? at [7:54]

Location: europe-central2
Job ID: airflow_1697283626942444_1f52de9e4cedebeb65456d77e49e6a29
; 1487)
[2023-10-14T11:40:28.155+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-10-14T11:40:28.173+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
