[2023-10-14T11:33:38.177+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:33:37.480280+00:00 [queued]>
[2023-10-14T11:33:38.182+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:33:37.480280+00:00 [queued]>
[2023-10-14T11:33:38.183+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T11:33:38.183+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-14T11:33:38.183+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T11:33:38.191+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_table> on 2023-10-14 11:33:37.480280+00:00
[2023-10-14T11:33:38.197+0000] {standard_task_runner.py:55} INFO - Started process 1210 to run task
[2023-10-14T11:33:38.200+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigquery_data_load', 'create_table', 'manual__2023-10-14T11:33:37.480280+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_data_load.py', '--cfg-path', '/tmp/tmpefp2l8m0']
[2023-10-14T11:33:38.202+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask create_table
[2023-10-14T11:33:38.259+0000] {task_command.py:388} INFO - Running <TaskInstance: bigquery_data_load.create_table manual__2023-10-14T11:33:37.480280+00:00 [running]> on host 4c2fe63b7c62
[2023-10-14T11:33:38.302+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Niko
AIRFLOW_CTX_DAG_ID=bigquery_data_load
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-10-14T11:33:37.480280+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-14T11:33:37.480280+00:00
[2023-10-14T11:33:38.305+0000] {bigquery.py:1077} INFO - Executing: '
        SELECT * except (rank)
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY vehicle_id ORDER BY DATE_TIME(date, TIME(hour, minute, 0)) DESC
                ) as rank
            FROM `***-400718.vehicle_analytics.history`) as latest
        WHERE rank = 1;
        
[2023-10-14T11:33:38.306+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-14T11:33:38.308+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:2051 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-10-14T11:33:38.308+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2023-10-14T11:33:38.311+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1103, in execute
    encryption_configuration=self.encryption_configuration,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2102, in run_query
    table_input=destination_dataset_table, default_project_id=self.project_id
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2209, in split_tablename
    raise ValueError(f"Expected table name in the format of <dataset>.<table>. Got: {table_input}")
ValueError: Expected table name in the format of <dataset>.<table>. Got: latest
[2023-10-14T11:33:38.318+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigquery_data_load, task_id=create_table, execution_date=20231014T113337, start_date=20231014T113338, end_date=20231014T113338
[2023-10-14T11:33:38.325+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task create_table (Expected table name in the format of <dataset>.<table>. Got: latest; 1210)
[2023-10-14T11:33:38.335+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-10-14T11:33:38.347+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
